function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "layout.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (title) {
jade_debug.unshift(new jade.DebugItem( 0, "layout.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "layout.jade" ));
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 2, "layout.jade" ));
buf.push("<html>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "layout.jade" ));
buf.push("<head>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "layout.jade" ));
buf.push("<title>" + (jade.escape(null == (jade_interp = title) ? "" : jade_interp)));
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "layout.jade" ));
buf.push("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "layout.jade" ));
buf.push("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 7, "layout.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"/stylesheets/style.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "layout.jade" ));
buf.push("<!-- Office JavaScript API -->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "layout.jade" ));
buf.push("<script type=\"text/javascript\" src=\"https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 11, "layout.jade" ));
buf.push("<link rel'stylesheep href=\"https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.0/css/fabric.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 12, "layout.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "layout.jade" ));
buf.push("<!-- LinkedIn Javascript API-->");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 15, "layout.jade" ));
buf.push("<script type=\"text/javascript\" src=\"https://platform.linkedin.com/in.js\">");
jade_debug.unshift(new jade.DebugItem( 20, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 20, jade_debug[0].filename ));
buf.push("api_key:   866im7uijeojq4");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 20, jade_debug[0].filename ));
buf.push("onLoad:    linkedin_loaded");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 20, jade_debug[0].filename ));
buf.push("authorize: true");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 20, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 20, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 21, "layout.jade" ));
buf.push("<body class=\"ms-font-m ms-welcome\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 22, "layout.jade" ));
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 23, "layout.jade" ));
buf.push("<script type=\"text/javascript\" src=\"/jscripts/jquery.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 24, "layout.jade" ));
buf.push("<script type=\"text/javascript\" src=\"/scripts/app.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 25, "layout.jade" ));
buf.push("<script src=\"https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();}.call(this,"title" in locals_for_with?locals_for_with.title:typeof title!=="undefined"?title:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\nhtml\n  head\n    title= title\n    meta(http-equiv=\"X-UA-Compatible\", content=\"IE=Edge\")\n    meta(name='viewport', content='width=device-width, initial-scale=1.0')\n    link(rel='stylesheet', href='/stylesheets/style.css')\n\n    <!-- Office JavaScript API -->\n    script(type='text/javascript', src='https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js')\n    link(rel'stylesheep', href=\"https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.0/css/fabric.css\")\n    link(rel=\"stylesheet\", href=\"https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css\")\n\n    <!-- LinkedIn Javascript API-->\n    script(type=\"text/javascript\" src=\"https://platform.linkedin.com/in.js\").\n        api_key:   866im7uijeojq4\n        onLoad:    linkedin_loaded\n        authorize: true\n\n    \n  body.ms-font-m.ms-welcome\n    block content\n    script(type='text/javascript', src='/jscripts/jquery.js')\n    script(type='text/javascript', src='/scripts/app.js')\n    script(src='https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js')");
}
}